# Generated by Django 4.2 on 2023-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkbox',
            field=models.BooleanField(null=True),
        ),
    ]
