# Generated by Django 4.2 on 2023-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='checkbox',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
